import {ChevronRight} from 'lucide-react';
import {format,parseISO} from 'date-fns';
import type {CardioEntry,StrengthEntry} from '../types/health';

const sum=(values:(number|null|undefined)[])=>values.reduce<number>((a,b)=>a+(b??0),0);
function strengthTitle(entries:StrengthEntry[]){const text=entries.flatMap(x=>x.primaryBodyParts).join(' ');if(/Glutes|Quadriceps|Hamstrings/.test(text))return '臀腿训练';if(/Chest/.test(text))return /Core/.test(text)?'胸部 + 核心训练':'胸部训练';if(/Back/.test(text)&&/Shoulders/.test(text))return '肩背训练';if(/Back/.test(text))return '背部训练';if(/Shoulders/.test(text))return '肩部训练';return '力量训练'}
const lb=(kg:number|null|undefined)=>kg==null?'自重 / 未记录':`${Math.round(kg*2.20462)} lb`;

export function DailyExerciseList({cardio,strength,onDelete}:{cardio:CardioEntry[];strength:StrengthEntry[];onDelete:(kind:'cardioEntries'|'strengthEntries',id:string)=>void}){
  const dates=[...new Set([...cardio,...strength].map(x=>x.date))].sort().reverse();
  return <section className="panel daily-training"><div className="daily-training-head"><div><h3>每日训练记录</h3><p className="muted">左侧有氧 · 右侧无氧</p></div><div className="training-key"><span><i className="green"/>有氧</span><span><i className="red"/>无氧</span></div></div><div className="training-days">{dates.map(date=>{const c=cardio.filter(x=>x.date===date),s=strength.filter(x=>x.date===date),cMinutes=Math.round(sum(c.map(x=>x.durationMinutes))),sMinutes=Math.round(sum(s.map(x=>x.durationMinutes))),cKcal=Math.round(sum(c.map(x=>x.caloriesBurnedKcal))),sKcal=Math.round(sum(s.map(x=>x.caloriesBurnedKcal)));return <details className="training-day" key={date}><summary><time className="training-date">{format(parseISO(date),'M/d')}</time><div className="training-half cardio-half"><b>{c.length?c.map(x=>x.activityName||x.activityType).join(' + '):'无有氧'}</b><span>{c.length?`${cMinutes} 分钟${cKcal?` · ${cKcal} kcal`:''}`:'—'}</span></div><div className="training-half strength-half"><b>{s.length?strengthTitle(s):'无无氧'}</b><span>{s.length?`${sMinutes||'—'} 分钟 · ${s.length} 个动作${sKcal?` · ${sKcal} kcal`:''}`:'—'}</span></div><ChevronRight size={18}/></summary><div className="training-expanded"><time className="training-date">{format(parseISO(date),'M/d')}</time><div className="training-detail cardio-detail"><h4>有氧</h4>{c.length?c.map(x=><div className="training-item" key={x.id}><div><b>{x.activityName||x.activityType}</b><span>{x.durationMinutes??'—'} 分钟 · {x.caloriesBurnedKcal??'—'} kcal{x.averageHeartRateBpm?` · 平均心率 ${x.averageHeartRateBpm}`:''}</span></div><button className="delete" onClick={()=>onDelete('cardioEntries',x.id)}>删除</button></div>):<p>当天没有有氧记录</p>}</div><div className="training-detail strength-detail"><h4>无氧</h4>{s.length?s.map(x=><div className="training-item" key={x.id}><div><b>{x.exerciseName}</b><span>{x.sets??'—'} 组 · {x.totalReps??'—'} 次 · {lb(x.weightKg)}</span>{x.sourceText&&<p>{x.sourceText}</p>}</div><button className="delete" onClick={()=>onDelete('strengthEntries',x.id)}>删除</button></div>):<p>当天没有无氧记录</p>}</div></div></details>})}</div></section>
}
